controller_manager:
  ros__parameters:
    # Can be bigger, should not break anything
    update_rate: 1  # Hz

    r_pinky_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    r_ring_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    r_middle_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    r_index_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    r_thumb_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    r_lower_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    r_upper_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    head_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    eyes_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    forward_head_controller:
      type: forward_command_controller/ForwardCommandController

    jaw_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

# Set joint state broadcaster to push zero joint states to all other than movable joints
joint_state_broadcaster:
  ros__parameters:
    extra_joints:
    - head_roll_joint
    - head_tilt_joint
    - waist_pan_joint
    - waist_roll_joint
    - l_shoulder_lift_joint
    - l_upper_arm_roll_joint
    - l_elbow_flex_joint
    - l_shoulder_out_joint
    - l_thumb1_joint
    - l_thumb_joint
    - l_thumb3_joint
    - l_index1_joint
    - l_index_joint
    - l_index3_joint
    - l_middle1_joint
    - l_middle_joint
    - l_middle3_joint
    - l_ring1_joint
    - l_ring_joint
    - l_ring3_joint
    - l_ring4_joint
    - l_pinky1_joint
    - l_pinky_joint
    - l_pinky3_joint
    - l_pinky4_joint
    - l_wrist_roll_joint


head_controller:
  ros__parameters:
    joints:
    - head_pan_joint
    - head_tilt_right_joint
    - head_tilt_left_joint
    - head_tilt_vertical_joint
    write_op_modes:
    - head_pan_joint
    - head_tilt_right_joint
    - head_tilt_left_joint
    - head_tilt_vertical_joint
    allow_partial_joints_goal: true
    interface_name: position

    # Seems like this settings is required by jointtrajectory controller type
    command_interfaces:
      - position
    state_interfaces:
      - position

    # Now only 1hz rate, can be changed to bigger
    state_publish_rate: 1.0 # Defaults to 50
    action_monitor_rate: 1.0 # Defaults to 20

eyes_controller:
  ros__parameters:
    joints:
    - eyes_shift_vertical_joint
    - eyes_shift_horizontal_joint
    write_op_modes:
    - eyes_shift_vertical_joint
    - eyes_shift_horizontal_joint
    allow_partial_joints_goal: true
    interface_name: position

    command_interfaces:
      - position
    state_interfaces:
      - position

    state_publish_rate: 1.0 # Defaults to 50
    action_monitor_rate: 1.0 # Defaults to 20

jaw_controller:
  ros__parameters:
    joints:
    - head_jaw_joint
    write_op_modes:
    - head_jaw_joint
    interface_name: position

    command_interfaces:
      - position
    state_interfaces:
      - position

    state_publish_rate: 1.0 # Defaults to 50
    action_monitor_rate: 1.0 # Defaults to 20


r_pinky_controller:
  ros__parameters:
    joints:
    - r_pinky_joint
    write_op_modes:
    - r_pinky_joint
    interface_name: position

    command_interfaces:
      - position
    state_interfaces:
      - position
    
    state_publish_rate: 1.0 # In Hz, Defaults to 50
    action_monitor_rate: 1.0 # In Hz, Defaults to 20

r_ring_controller:
  ros__parameters:
    joints:
    - r_ring_joint
    write_op_modes:
    - r_ring_joint
    interface_name: position

    command_interfaces:
      - position
    state_interfaces:
      - position
    
    state_publish_rate: 1.0 # In Hz, Defaults to 50
    action_monitor_rate: 1.0 # In Hz, Defaults to 20

r_middle_controller:
  ros__parameters:
    joints:
    - r_middle_joint
    write_op_modes:
    - r_middle_joint
    interface_name: position

    command_interfaces:
      - position
    state_interfaces:
      - position
    
    state_publish_rate: 1.0 # In Hz, Defaults to 50
    action_monitor_rate: 1.0 # In Hz, Defaults to 20

r_index_controller:
  ros__parameters:
    joints:
    - r_index_joint
    write_op_modes:
    - r_index_joint
    interface_name: position

    command_interfaces:
      - position
    state_interfaces:
      - position
    
    state_publish_rate: 1.0 # In Hz, Defaults to 50
    action_monitor_rate: 1.0 # In Hz, Defaults to 20

r_thumb_controller:
  ros__parameters:
    joints:
    - r_thumb_joint
    write_op_modes:
    - r_thumb_joint
    interface_name: position

    command_interfaces:
      - position
    state_interfaces:
      - position
    
    state_publish_rate: 1.0 # In Hz, Defaults to 50
    action_monitor_rate: 1.0 # In Hz, Defaults to 20

r_lower_arm_controller:
  ros__parameters:
    joints:
    - r_elbow_flex_joint
    - r_wrist_roll_joint
    write_op_modes:
    - r_elbow_flex_joint
    - r_wrist_roll_joint
    interface_name: position

    command_interfaces:
      - position
    state_interfaces:
      - position
    
    state_publish_rate: 1.0 # In Hz, Defaults to 50
    action_monitor_rate: 1.0 # In Hz, Defaults to 20

r_upper_arm_controller:
  ros__parameters:
    joints:
    - r_shoulder_lift_joint
    - r_shoulder_out_joint
    - r_upper_arm_roll_joint
    write_op_modes:
    - r_shoulder_lift_joint
    - r_shoulder_out_joint
    - r_upper_arm_roll_joint
    interface_name: position

    command_interfaces:
      - position
    state_interfaces:
      - position

    state_publish_rate: 1.0 # In Hz, Defaults to 50
    action_monitor_rate: 1.0 # In Hz, Defaults to 20