controller_manager:
  ros__parameters:
    # Can be bigger, should not break anything
    update_rate: 1  # Hz

    head_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    eyes_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    forward_head_controller:
      type: forward_command_controller/ForwardCommandController

    jaw_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

# Set joint state broadcaster to push zero joint states to all other than movable joints
joint_state_broadcaster:
  ros__parameters:
    extra_joints:
    - head_roll_joint
    - head_tilt_joint
    - waist_pan_joint
    - waist_roll_joint

head_controller:
  ros__parameters:
    joints:
    - head_pan_joint
    - head_tilt_right_joint
    - head_tilt_left_joint
    - head_tilt_vertical_joint
    write_op_modes:
    - head_pan_joint
    - head_tilt_right_joint
    - head_tilt_left_joint
    - head_tilt_vertical_joint
    allow_partial_joints_goal: true
    interface_name: position

    # Seems like this settings is required by jointtrajectory controller type
    command_interfaces:
      - position
    state_interfaces:
      - position

    # Now only 1hz rate, can be changed to bigger
    state_publish_rate: 1.0 # Defaults to 50
    action_monitor_rate: 1.0 # Defaults to 20

eyes_controller:
  ros__parameters:
    joints:
    - eyes_shift_vertical_joint
    - eyes_shift_horizontal_joint
    write_op_modes:
    - eyes_shift_vertical_joint
    - eyes_shift_horizontal_joint
    allow_partial_joints_goal: true
    interface_name: position

    command_interfaces:
      - position
    state_interfaces:
      - position

    state_publish_rate: 1.0 # Defaults to 50
    action_monitor_rate: 1.0 # Defaults to 20

jaw_controller:
  ros__parameters:
    joints:
    - head_jaw_joint
    write_op_modes:
    - head_jaw_joint
    interface_name: position

    command_interfaces:
      - position
    state_interfaces:
      - position

    state_publish_rate: 1.0 # Defaults to 50
    action_monitor_rate: 1.0 # Defaults to 20
