fake_joint_driver_node:
  ros__parameters:
    start_position:
      joints:
        - head_pan_joint
        - head_tilt_right_joint
        - head_tilt_left_joint
        - head_tilt_vertical_joint
        - head_jaw_joint
        - eyes_shift_horizontal_joint
        - r_shoulder_lift_joint
        - r_pinky1_joint
        - r_pinky_joint
        - r_pinky3_joint
        - r_pinky4_joint
        - r_ring1_joint
        - r_ring_joint
        - r_ring3_joint
        - r_ring4_joint
        - r_middle1_joint
        - r_middle_joint
        - r_middle3_joint
        - r_index1_joint
        - r_index_joint
        - r_index3_joint
        - r_thumb1_joint
        - r_thumb_joint
        - r_thumb3_joint
        - r_elbow_flex_joint
        - r_wrist_roll_joint
        - r_shoulder_lift_joint
        - r_shoulder_out_joint
        - r_upper_arm_roll_joint
      values:
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0