# You can find control table of Dynamixel on emanual (http://emanual.robotis.com/#control-table)
# Control table item has to be set Camel_Case and not included whitespace
# You are supposed to set at least Dynamixel ID

head_tilt_right_joint:
  ID: 1

head_tilt_vertical_joint:
  ID: 2

head_tilt_left_joint:
  ID: 3

head_pan_joint:
  ID: 4
  Drive_Mode: 0 # Velocity-based Profile, default actually

eyes_shift_horizontal_joint:
  ID: 10

eyes_shift_vertical_joint:
  ID: 11

head_jaw_joint:
  ID: 12

r_shoulder_lift_joint:
 ID: 21

 r_shoulder_out_joint:
 ID: 22

 r_upper_arm_roll_joint:
 ID: 23

 r_elbow_flex_joint:
 ID: 24

 r_wrist_roll_joint:
 ID: 25

 r_thumb_joint:
 ID: 31

 r_thumb1_joint:
 ID: 32

 r_thumb3_joint:
 ID: 33

 r_index_joint:
 ID: 34

 r_index1_joint:
 ID: 35

 r_index3_joint:
 ID: 36

 r_middle_joint:
 ID: 37

 r_middle1_joint:
 ID: 38

 r_middle3_joint:
 ID: 39

 r_ring_joint:
 ID: 40

 r_ring1_joint:
 ID: 41

 r_ring3_joint:
 ID: 42

 r_ring4_joint:
 ID: 43

 r_pinky_joint:
 ID: 44

 r_pinky1_joint:
 ID: 45

 r_pinky3_joint:
 ID: 46

 r_pinky4_joint:
 ID: 47
